
-- --------------------------------------------------
-- Entity Designer DDL Script for SQL Server 2005, 2008, 2012 and Azure
-- --------------------------------------------------
-- Date Created: 02/27/2017 20:56:17
-- Generated from EDMX file: C:\Users\PaulPlaza\Source\Repos\SwParqueadero\SwParqueadero\SwParqueadero.AccesoDatos\DcParqueaderoModel.edmx
-- --------------------------------------------------

SET QUOTED_IDENTIFIER OFF;
GO
USE [DbParqueo];
GO
IF SCHEMA_ID(N'dbo') IS NULL EXECUTE(N'CREATE SCHEMA [dbo]');
GO

-- --------------------------------------------------
-- Dropping existing FOREIGN KEY constraints
-- --------------------------------------------------

IF OBJECT_ID(N'[dbo].[FK_TBL_ASIGNACION_PARQUEADERO_TBL_JORNADA]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TBL_ASIGNACION_PARQUEADERO] DROP CONSTRAINT [FK_TBL_ASIGNACION_PARQUEADERO_TBL_JORNADA];
GO
IF OBJECT_ID(N'[dbo].[FK_TBL_ASIGNACION_PARQUEADERO_TBL_PUESTOS]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TBL_ASIGNACION_PARQUEADERO] DROP CONSTRAINT [FK_TBL_ASIGNACION_PARQUEADERO_TBL_PUESTOS];
GO
IF OBJECT_ID(N'[dbo].[FK_TBL_ASIGNACION_PARQUEADERO_TBL_SOLICITUD]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TBL_ASIGNACION_PARQUEADERO] DROP CONSTRAINT [FK_TBL_ASIGNACION_PARQUEADERO_TBL_SOLICITUD];
GO
IF OBJECT_ID(N'[dbo].[FK_TBL_DIA_ASIGNACION_TBL_ASIGNACION_PARQUEADERO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TBL_DIA_ASIGNACION] DROP CONSTRAINT [FK_TBL_DIA_ASIGNACION_TBL_ASIGNACION_PARQUEADERO];
GO
IF OBJECT_ID(N'[dbo].[FK_TBL_DIA_ASIGNACION_TBL_DIAS]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TBL_DIA_ASIGNACION] DROP CONSTRAINT [FK_TBL_DIA_ASIGNACION_TBL_DIAS];
GO
IF OBJECT_ID(N'[dbo].[FK_TBL_MODELO_TBL_MARCA]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TBL_MODELO] DROP CONSTRAINT [FK_TBL_MODELO_TBL_MARCA];
GO
IF OBJECT_ID(N'[dbo].[FK_TBL_OBSERVACION_SOLICITUD_TBL_OBSERVACIONES]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TBL_OBSERVACION_SOLICITUD] DROP CONSTRAINT [FK_TBL_OBSERVACION_SOLICITUD_TBL_OBSERVACIONES];
GO
IF OBJECT_ID(N'[dbo].[FK_TBL_OBSERVACION_SOLICITUD_TBL_SOLICITUD]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TBL_OBSERVACION_SOLICITUD] DROP CONSTRAINT [FK_TBL_OBSERVACION_SOLICITUD_TBL_SOLICITUD];
GO
IF OBJECT_ID(N'[dbo].[FK_TBL_PUESTOS_TBL_DIMENSION]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TBL_PUESTOS] DROP CONSTRAINT [FK_TBL_PUESTOS_TBL_DIMENSION];
GO
IF OBJECT_ID(N'[dbo].[FK_TBL_PUESTOS_TBL_PARQUEADERO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TBL_PUESTOS] DROP CONSTRAINT [FK_TBL_PUESTOS_TBL_PARQUEADERO];
GO
IF OBJECT_ID(N'[dbo].[FK_TBL_REQUISITOS_TBL_SOLICITUD]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TBL_REQUISITOS] DROP CONSTRAINT [FK_TBL_REQUISITOS_TBL_SOLICITUD];
GO
IF OBJECT_ID(N'[dbo].[FK_TBL_SOLICITUD_TBL_USUARIO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TBL_SOLICITUD] DROP CONSTRAINT [FK_TBL_SOLICITUD_TBL_USUARIO];
GO
IF OBJECT_ID(N'[dbo].[FK_TBL_USUARIO_TBL_TIPO_USUARIO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TBL_USUARIO] DROP CONSTRAINT [FK_TBL_USUARIO_TBL_TIPO_USUARIO];
GO
IF OBJECT_ID(N'[dbo].[FK_TBL_VEHICULO_TBL_DIMENSION]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TBL_VEHICULO] DROP CONSTRAINT [FK_TBL_VEHICULO_TBL_DIMENSION];
GO
IF OBJECT_ID(N'[dbo].[FK_TBL_VEHICULO_TBL_MODELO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TBL_VEHICULO] DROP CONSTRAINT [FK_TBL_VEHICULO_TBL_MODELO];
GO
IF OBJECT_ID(N'[dbo].[FK_TBL_VEHICULO_TBL_USUARIO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[TBL_VEHICULO] DROP CONSTRAINT [FK_TBL_VEHICULO_TBL_USUARIO];
GO

-- --------------------------------------------------
-- Dropping existing tables
-- --------------------------------------------------

IF OBJECT_ID(N'[dbo].[sysdiagrams]', 'U') IS NOT NULL
    DROP TABLE [dbo].[sysdiagrams];
GO
IF OBJECT_ID(N'[dbo].[TBL_ASIGNACION_PARQUEADERO]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TBL_ASIGNACION_PARQUEADERO];
GO
IF OBJECT_ID(N'[dbo].[TBL_DIA_ASIGNACION]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TBL_DIA_ASIGNACION];
GO
IF OBJECT_ID(N'[dbo].[TBL_DIAS]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TBL_DIAS];
GO
IF OBJECT_ID(N'[dbo].[TBL_DIMENSION]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TBL_DIMENSION];
GO
IF OBJECT_ID(N'[dbo].[TBL_EMPRESA]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TBL_EMPRESA];
GO
IF OBJECT_ID(N'[dbo].[TBL_JORNADA]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TBL_JORNADA];
GO
IF OBJECT_ID(N'[dbo].[TBL_MARCA]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TBL_MARCA];
GO
IF OBJECT_ID(N'[dbo].[TBL_MODELO]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TBL_MODELO];
GO
IF OBJECT_ID(N'[dbo].[TBL_OBSERVACION_SOLICITUD]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TBL_OBSERVACION_SOLICITUD];
GO
IF OBJECT_ID(N'[dbo].[TBL_OBSERVACIONES]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TBL_OBSERVACIONES];
GO
IF OBJECT_ID(N'[dbo].[TBL_PARQUEADERO]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TBL_PARQUEADERO];
GO
IF OBJECT_ID(N'[dbo].[TBL_PUESTOS]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TBL_PUESTOS];
GO
IF OBJECT_ID(N'[dbo].[TBL_REQUISITOS]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TBL_REQUISITOS];
GO
IF OBJECT_ID(N'[dbo].[TBL_SOLICITUD]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TBL_SOLICITUD];
GO
IF OBJECT_ID(N'[dbo].[TBL_TIPO_USUARIO]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TBL_TIPO_USUARIO];
GO
IF OBJECT_ID(N'[dbo].[TBL_USUARIO]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TBL_USUARIO];
GO
IF OBJECT_ID(N'[dbo].[TBL_VEHICULO]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TBL_VEHICULO];
GO

-- --------------------------------------------------
-- Creating all tables
-- --------------------------------------------------

-- Creating table 'TBL_ASIGNACION_PARQUEADERO'
CREATE TABLE [dbo].[TBL_ASIGNACION_PARQUEADERO] (
    [ASI_CODIGO] int  NOT NULL,
    [ASI_DESCRIPCION] varchar(150)  NOT NULL,
    [JOR_CODIGO] int  NOT NULL,
    [SOL_CODIGO] int  NOT NULL,
    [PUE_CODIGO] int  NOT NULL
);
GO

-- Creating table 'TBL_DIA_ASIGNACION'
CREATE TABLE [dbo].[TBL_DIA_ASIGNACION] (
    [ADIA_CODIGO] int  NOT NULL,
    [DIA_CODIGO] int  NOT NULL,
    [ASI_CODIGO] int  NOT NULL
);
GO

-- Creating table 'TBL_DIAS'
CREATE TABLE [dbo].[TBL_DIAS] (
    [DIA_CODIGO] int  NOT NULL,
    [DIA_DESCRIPCION] varchar(15)  NOT NULL
);
GO

-- Creating table 'TBL_JORNADA'
CREATE TABLE [dbo].[TBL_JORNADA] (
    [JOR_CODIGO] int  NOT NULL,
    [JOR_DESCRIPCION] varchar(50)  NOT NULL,
    [JOR_HORA] varchar(50)  NOT NULL
);
GO

-- Creating table 'TBL_MARCA'
CREATE TABLE [dbo].[TBL_MARCA] (
    [MAR_CODIGO] int  NOT NULL,
    [MAR_DESCRIPCION] varchar(50)  NULL
);
GO

-- Creating table 'TBL_MODELO'
CREATE TABLE [dbo].[TBL_MODELO] (
    [MOD_CODIGO] int  NOT NULL,
    [MOD_DESCRIPCION] varchar(50)  NOT NULL,
    [MAR_CODIGO] int  NOT NULL
);
GO

-- Creating table 'TBL_OBSERVACION_SOLICITUD'
CREATE TABLE [dbo].[TBL_OBSERVACION_SOLICITUD] (
    [OBDOL_CODIGI] int  NOT NULL,
    [OBS_CODIGO] int  NOT NULL,
    [SOL_CODIGO] int  NOT NULL
);
GO

-- Creating table 'TBL_OBSERVACIONES'
CREATE TABLE [dbo].[TBL_OBSERVACIONES] (
    [OBS_CODIGO] int  NOT NULL,
    [OBS_DESCRIPCION] varchar(150)  NULL,
    [OBS_USU] varchar(150)  NULL
);
GO

-- Creating table 'TBL_PARQUEADERO'
CREATE TABLE [dbo].[TBL_PARQUEADERO] (
    [PAR_CODIGO] int  NOT NULL,
    [PAR_DESCRIPCION] varchar(50)  NOT NULL,
    [PAR_DIRECCION] varchar(50)  NOT NULL,
    [PAR_ENCARGADO] varchar(50)  NOT NULL,
    [PAR_CONTACTO] varchar(50)  NOT NULL,
    [PAR_PUESTOS] int  NOT NULL,
    [PAR_CONTACTO2] varchar(50)  NULL,
    [PAR_TELEFONO] varchar(50)  NOT NULL,
    [PAR_TELEFONO2] varchar(50)  NULL,
    [PAR_TELEFONO_ENCARGADO] varchar(50)  NOT NULL
);
GO

-- Creating table 'TBL_PUESTOS'
CREATE TABLE [dbo].[TBL_PUESTOS] (
    [PUE_CODIGO] int  NOT NULL,
    [PUE_NOMBRE] varchar(50)  NOT NULL,
    [DIM_CODIGO] int  NOT NULL,
    [PAR_CODIGO] int  NOT NULL,
    [PUE_ESTADO_MATUTINA] bit  NOT NULL,
    [PUE_ESTADO_NOCTURNO] bit  NOT NULL
);
GO

-- Creating table 'TBL_REQUISITOS'
CREATE TABLE [dbo].[TBL_REQUISITOS] (
    [REQ_CODIGO] int  NOT NULL,
    [REQ_FACTURA] bit  NOT NULL,
    [REQ_LICENCIA] bit  NOT NULL,
    [REQ_CARNET_CONADIS] bit  NOT NULL,
    [REQ_MATRICULA_VEHICULAR] bit  NOT NULL,
    [SOL_CODIGO] int  NOT NULL,
    [REQ_FACTURA_IMAGEN] varchar(150)  NOT NULL,
    [REQ_LICENCIA_IMAGEN] varchar(150)  NOT NULL,
    [REQ_CARNET_CONADIS_IMAGEN] varchar(150)  NOT NULL,
    [REQ_MATRICULA_IMAGEN] varchar(150)  NOT NULL
);
GO

-- Creating table 'TBL_SOLICITUD'
CREATE TABLE [dbo].[TBL_SOLICITUD] (
    [SOL_CODIGO] int  NOT NULL,
    [SOL_FECHA_INICIO] datetime  NULL,
    [SOL_FECHA_APROBACION] datetime  NULL,
    [USU_CODIGO] int  NULL,
    [PER_DESCRIPCION] varchar(50)  NULL,
    [SOL_APROBADO] bit  NULL,
    [SOL_BANDEJA] char(1)  NULL
);
GO

-- Creating table 'TBL_TIPO_USUARIO'
CREATE TABLE [dbo].[TBL_TIPO_USUARIO] (
    [TIPU_CODIGO] int  NOT NULL,
    [TIPU_DESCRIPCION] varchar(50)  NOT NULL
);
GO

-- Creating table 'TBL_VEHICULO'
CREATE TABLE [dbo].[TBL_VEHICULO] (
    [VEH_CODIGO] int  NOT NULL,
    [VEH_OBSERVACION] varchar(50)  NOT NULL,
    [VEH_PLACA] varchar(10)  NOT NULL,
    [VEH_FOTO] varchar(200)  NULL,
    [MOD_CODIGO] int  NOT NULL,
    [DIM_CODIGO] int  NOT NULL,
    [USU_CODIGO] int  NOT NULL,
    [VEH_ESTADO] bit  NOT NULL
);
GO

-- Creating table 'TBL_USUARIO'
CREATE TABLE [dbo].[TBL_USUARIO] (
    [USU_CODIGO] int  NOT NULL,
    [USU_NOMBRES] varchar(50)  NOT NULL,
    [USU_APELLIDOS] varchar(50)  NOT NULL,
    [USU_ESTADO] bit  NOT NULL,
    [TIPU_CODIGO] int  NOT NULL,
    [USU_CEDULA] varchar(50)  NOT NULL,
    [USU_CORREO] varchar(50)  NOT NULL,
    [USU_CONTACTO] varchar(50)  NOT NULL,
    [USU_PASSWORD] varchar(50)  NOT NULL
);
GO

-- Creating table 'sysdiagrams'
CREATE TABLE [dbo].[sysdiagrams] (
    [name] nvarchar(128)  NOT NULL,
    [principal_id] int  NOT NULL,
    [diagram_id] int IDENTITY(1,1) NOT NULL,
    [version] int  NULL,
    [definition] varbinary(max)  NULL
);
GO

-- Creating table 'TBL_DIMENSION'
CREATE TABLE [dbo].[TBL_DIMENSION] (
    [DIM_CODIGO] int  NOT NULL,
    [DIM_DESCRIPCION] nchar(10)  NOT NULL,
    [DIM_LARGO] decimal(4,2)  NOT NULL,
    [DIM_ANCHO] decimal(4,2)  NOT NULL
);
GO

-- Creating table 'TBL_EMPRESA'
CREATE TABLE [dbo].[TBL_EMPRESA] (
    [EMP_CODIGO] int  NOT NULL,
    [EMP_NOMBRE] varchar(50)  NOT NULL,
    [EMP_CORREO] varchar(50)  NOT NULL,
    [EMP_SMTP] varchar(50)  NOT NULL,
    [EMP_PUERTO] varchar(50)  NOT NULL,
    [EMP_PASSWORD] varchar(50)  NULL
);
GO

-- --------------------------------------------------
-- Creating all PRIMARY KEY constraints
-- --------------------------------------------------

-- Creating primary key on [ASI_CODIGO] in table 'TBL_ASIGNACION_PARQUEADERO'
ALTER TABLE [dbo].[TBL_ASIGNACION_PARQUEADERO]
ADD CONSTRAINT [PK_TBL_ASIGNACION_PARQUEADERO]
    PRIMARY KEY CLUSTERED ([ASI_CODIGO] ASC);
GO

-- Creating primary key on [ADIA_CODIGO] in table 'TBL_DIA_ASIGNACION'
ALTER TABLE [dbo].[TBL_DIA_ASIGNACION]
ADD CONSTRAINT [PK_TBL_DIA_ASIGNACION]
    PRIMARY KEY CLUSTERED ([ADIA_CODIGO] ASC);
GO

-- Creating primary key on [DIA_CODIGO] in table 'TBL_DIAS'
ALTER TABLE [dbo].[TBL_DIAS]
ADD CONSTRAINT [PK_TBL_DIAS]
    PRIMARY KEY CLUSTERED ([DIA_CODIGO] ASC);
GO

-- Creating primary key on [JOR_CODIGO] in table 'TBL_JORNADA'
ALTER TABLE [dbo].[TBL_JORNADA]
ADD CONSTRAINT [PK_TBL_JORNADA]
    PRIMARY KEY CLUSTERED ([JOR_CODIGO] ASC);
GO

-- Creating primary key on [MAR_CODIGO] in table 'TBL_MARCA'
ALTER TABLE [dbo].[TBL_MARCA]
ADD CONSTRAINT [PK_TBL_MARCA]
    PRIMARY KEY CLUSTERED ([MAR_CODIGO] ASC);
GO

-- Creating primary key on [MOD_CODIGO] in table 'TBL_MODELO'
ALTER TABLE [dbo].[TBL_MODELO]
ADD CONSTRAINT [PK_TBL_MODELO]
    PRIMARY KEY CLUSTERED ([MOD_CODIGO] ASC);
GO

-- Creating primary key on [OBDOL_CODIGI] in table 'TBL_OBSERVACION_SOLICITUD'
ALTER TABLE [dbo].[TBL_OBSERVACION_SOLICITUD]
ADD CONSTRAINT [PK_TBL_OBSERVACION_SOLICITUD]
    PRIMARY KEY CLUSTERED ([OBDOL_CODIGI] ASC);
GO

-- Creating primary key on [OBS_CODIGO] in table 'TBL_OBSERVACIONES'
ALTER TABLE [dbo].[TBL_OBSERVACIONES]
ADD CONSTRAINT [PK_TBL_OBSERVACIONES]
    PRIMARY KEY CLUSTERED ([OBS_CODIGO] ASC);
GO

-- Creating primary key on [PAR_CODIGO] in table 'TBL_PARQUEADERO'
ALTER TABLE [dbo].[TBL_PARQUEADERO]
ADD CONSTRAINT [PK_TBL_PARQUEADERO]
    PRIMARY KEY CLUSTERED ([PAR_CODIGO] ASC);
GO

-- Creating primary key on [PUE_CODIGO] in table 'TBL_PUESTOS'
ALTER TABLE [dbo].[TBL_PUESTOS]
ADD CONSTRAINT [PK_TBL_PUESTOS]
    PRIMARY KEY CLUSTERED ([PUE_CODIGO] ASC);
GO

-- Creating primary key on [REQ_CODIGO] in table 'TBL_REQUISITOS'
ALTER TABLE [dbo].[TBL_REQUISITOS]
ADD CONSTRAINT [PK_TBL_REQUISITOS]
    PRIMARY KEY CLUSTERED ([REQ_CODIGO] ASC);
GO

-- Creating primary key on [SOL_CODIGO] in table 'TBL_SOLICITUD'
ALTER TABLE [dbo].[TBL_SOLICITUD]
ADD CONSTRAINT [PK_TBL_SOLICITUD]
    PRIMARY KEY CLUSTERED ([SOL_CODIGO] ASC);
GO

-- Creating primary key on [TIPU_CODIGO] in table 'TBL_TIPO_USUARIO'
ALTER TABLE [dbo].[TBL_TIPO_USUARIO]
ADD CONSTRAINT [PK_TBL_TIPO_USUARIO]
    PRIMARY KEY CLUSTERED ([TIPU_CODIGO] ASC);
GO

-- Creating primary key on [VEH_CODIGO] in table 'TBL_VEHICULO'
ALTER TABLE [dbo].[TBL_VEHICULO]
ADD CONSTRAINT [PK_TBL_VEHICULO]
    PRIMARY KEY CLUSTERED ([VEH_CODIGO] ASC);
GO

-- Creating primary key on [USU_CODIGO] in table 'TBL_USUARIO'
ALTER TABLE [dbo].[TBL_USUARIO]
ADD CONSTRAINT [PK_TBL_USUARIO]
    PRIMARY KEY CLUSTERED ([USU_CODIGO] ASC);
GO

-- Creating primary key on [diagram_id] in table 'sysdiagrams'
ALTER TABLE [dbo].[sysdiagrams]
ADD CONSTRAINT [PK_sysdiagrams]
    PRIMARY KEY CLUSTERED ([diagram_id] ASC);
GO

-- Creating primary key on [DIM_CODIGO] in table 'TBL_DIMENSION'
ALTER TABLE [dbo].[TBL_DIMENSION]
ADD CONSTRAINT [PK_TBL_DIMENSION]
    PRIMARY KEY CLUSTERED ([DIM_CODIGO] ASC);
GO

-- Creating primary key on [EMP_CODIGO] in table 'TBL_EMPRESA'
ALTER TABLE [dbo].[TBL_EMPRESA]
ADD CONSTRAINT [PK_TBL_EMPRESA]
    PRIMARY KEY CLUSTERED ([EMP_CODIGO] ASC);
GO

-- --------------------------------------------------
-- Creating all FOREIGN KEY constraints
-- --------------------------------------------------

-- Creating foreign key on [JOR_CODIGO] in table 'TBL_ASIGNACION_PARQUEADERO'
ALTER TABLE [dbo].[TBL_ASIGNACION_PARQUEADERO]
ADD CONSTRAINT [FK_TBL_ASIGNACION_PARQUEADERO_TBL_JORNADA]
    FOREIGN KEY ([JOR_CODIGO])
    REFERENCES [dbo].[TBL_JORNADA]
        ([JOR_CODIGO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_TBL_ASIGNACION_PARQUEADERO_TBL_JORNADA'
CREATE INDEX [IX_FK_TBL_ASIGNACION_PARQUEADERO_TBL_JORNADA]
ON [dbo].[TBL_ASIGNACION_PARQUEADERO]
    ([JOR_CODIGO]);
GO

-- Creating foreign key on [PUE_CODIGO] in table 'TBL_ASIGNACION_PARQUEADERO'
ALTER TABLE [dbo].[TBL_ASIGNACION_PARQUEADERO]
ADD CONSTRAINT [FK_TBL_ASIGNACION_PARQUEADERO_TBL_PUESTOS]
    FOREIGN KEY ([PUE_CODIGO])
    REFERENCES [dbo].[TBL_PUESTOS]
        ([PUE_CODIGO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_TBL_ASIGNACION_PARQUEADERO_TBL_PUESTOS'
CREATE INDEX [IX_FK_TBL_ASIGNACION_PARQUEADERO_TBL_PUESTOS]
ON [dbo].[TBL_ASIGNACION_PARQUEADERO]
    ([PUE_CODIGO]);
GO

-- Creating foreign key on [SOL_CODIGO] in table 'TBL_ASIGNACION_PARQUEADERO'
ALTER TABLE [dbo].[TBL_ASIGNACION_PARQUEADERO]
ADD CONSTRAINT [FK_TBL_ASIGNACION_PARQUEADERO_TBL_SOLICITUD]
    FOREIGN KEY ([SOL_CODIGO])
    REFERENCES [dbo].[TBL_SOLICITUD]
        ([SOL_CODIGO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_TBL_ASIGNACION_PARQUEADERO_TBL_SOLICITUD'
CREATE INDEX [IX_FK_TBL_ASIGNACION_PARQUEADERO_TBL_SOLICITUD]
ON [dbo].[TBL_ASIGNACION_PARQUEADERO]
    ([SOL_CODIGO]);
GO

-- Creating foreign key on [ASI_CODIGO] in table 'TBL_DIA_ASIGNACION'
ALTER TABLE [dbo].[TBL_DIA_ASIGNACION]
ADD CONSTRAINT [FK_TBL_DIA_ASIGNACION_TBL_ASIGNACION_PARQUEADERO]
    FOREIGN KEY ([ASI_CODIGO])
    REFERENCES [dbo].[TBL_ASIGNACION_PARQUEADERO]
        ([ASI_CODIGO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_TBL_DIA_ASIGNACION_TBL_ASIGNACION_PARQUEADERO'
CREATE INDEX [IX_FK_TBL_DIA_ASIGNACION_TBL_ASIGNACION_PARQUEADERO]
ON [dbo].[TBL_DIA_ASIGNACION]
    ([ASI_CODIGO]);
GO

-- Creating foreign key on [DIA_CODIGO] in table 'TBL_DIA_ASIGNACION'
ALTER TABLE [dbo].[TBL_DIA_ASIGNACION]
ADD CONSTRAINT [FK_TBL_DIA_ASIGNACION_TBL_DIAS]
    FOREIGN KEY ([DIA_CODIGO])
    REFERENCES [dbo].[TBL_DIAS]
        ([DIA_CODIGO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_TBL_DIA_ASIGNACION_TBL_DIAS'
CREATE INDEX [IX_FK_TBL_DIA_ASIGNACION_TBL_DIAS]
ON [dbo].[TBL_DIA_ASIGNACION]
    ([DIA_CODIGO]);
GO

-- Creating foreign key on [MAR_CODIGO] in table 'TBL_MODELO'
ALTER TABLE [dbo].[TBL_MODELO]
ADD CONSTRAINT [FK_TBL_MODELO_TBL_MARCA]
    FOREIGN KEY ([MAR_CODIGO])
    REFERENCES [dbo].[TBL_MARCA]
        ([MAR_CODIGO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_TBL_MODELO_TBL_MARCA'
CREATE INDEX [IX_FK_TBL_MODELO_TBL_MARCA]
ON [dbo].[TBL_MODELO]
    ([MAR_CODIGO]);
GO

-- Creating foreign key on [MOD_CODIGO] in table 'TBL_VEHICULO'
ALTER TABLE [dbo].[TBL_VEHICULO]
ADD CONSTRAINT [FK_TBL_VEHICULO_TBL_MODELO]
    FOREIGN KEY ([MOD_CODIGO])
    REFERENCES [dbo].[TBL_MODELO]
        ([MOD_CODIGO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_TBL_VEHICULO_TBL_MODELO'
CREATE INDEX [IX_FK_TBL_VEHICULO_TBL_MODELO]
ON [dbo].[TBL_VEHICULO]
    ([MOD_CODIGO]);
GO

-- Creating foreign key on [OBS_CODIGO] in table 'TBL_OBSERVACION_SOLICITUD'
ALTER TABLE [dbo].[TBL_OBSERVACION_SOLICITUD]
ADD CONSTRAINT [FK_TBL_OBSERVACION_SOLICITUD_TBL_OBSERVACIONES]
    FOREIGN KEY ([OBS_CODIGO])
    REFERENCES [dbo].[TBL_OBSERVACIONES]
        ([OBS_CODIGO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_TBL_OBSERVACION_SOLICITUD_TBL_OBSERVACIONES'
CREATE INDEX [IX_FK_TBL_OBSERVACION_SOLICITUD_TBL_OBSERVACIONES]
ON [dbo].[TBL_OBSERVACION_SOLICITUD]
    ([OBS_CODIGO]);
GO

-- Creating foreign key on [SOL_CODIGO] in table 'TBL_OBSERVACION_SOLICITUD'
ALTER TABLE [dbo].[TBL_OBSERVACION_SOLICITUD]
ADD CONSTRAINT [FK_TBL_OBSERVACION_SOLICITUD_TBL_SOLICITUD]
    FOREIGN KEY ([SOL_CODIGO])
    REFERENCES [dbo].[TBL_SOLICITUD]
        ([SOL_CODIGO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_TBL_OBSERVACION_SOLICITUD_TBL_SOLICITUD'
CREATE INDEX [IX_FK_TBL_OBSERVACION_SOLICITUD_TBL_SOLICITUD]
ON [dbo].[TBL_OBSERVACION_SOLICITUD]
    ([SOL_CODIGO]);
GO

-- Creating foreign key on [PAR_CODIGO] in table 'TBL_PUESTOS'
ALTER TABLE [dbo].[TBL_PUESTOS]
ADD CONSTRAINT [FK_TBL_PUESTOS_TBL_PARQUEADERO]
    FOREIGN KEY ([PAR_CODIGO])
    REFERENCES [dbo].[TBL_PARQUEADERO]
        ([PAR_CODIGO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_TBL_PUESTOS_TBL_PARQUEADERO'
CREATE INDEX [IX_FK_TBL_PUESTOS_TBL_PARQUEADERO]
ON [dbo].[TBL_PUESTOS]
    ([PAR_CODIGO]);
GO

-- Creating foreign key on [SOL_CODIGO] in table 'TBL_REQUISITOS'
ALTER TABLE [dbo].[TBL_REQUISITOS]
ADD CONSTRAINT [FK_TBL_REQUISITOS_TBL_SOLICITUD]
    FOREIGN KEY ([SOL_CODIGO])
    REFERENCES [dbo].[TBL_SOLICITUD]
        ([SOL_CODIGO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_TBL_REQUISITOS_TBL_SOLICITUD'
CREATE INDEX [IX_FK_TBL_REQUISITOS_TBL_SOLICITUD]
ON [dbo].[TBL_REQUISITOS]
    ([SOL_CODIGO]);
GO

-- Creating foreign key on [USU_CODIGO] in table 'TBL_SOLICITUD'
ALTER TABLE [dbo].[TBL_SOLICITUD]
ADD CONSTRAINT [FK_TBL_SOLICITUD_TBL_USUARIO]
    FOREIGN KEY ([USU_CODIGO])
    REFERENCES [dbo].[TBL_USUARIO]
        ([USU_CODIGO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_TBL_SOLICITUD_TBL_USUARIO'
CREATE INDEX [IX_FK_TBL_SOLICITUD_TBL_USUARIO]
ON [dbo].[TBL_SOLICITUD]
    ([USU_CODIGO]);
GO

-- Creating foreign key on [TIPU_CODIGO] in table 'TBL_USUARIO'
ALTER TABLE [dbo].[TBL_USUARIO]
ADD CONSTRAINT [FK_TBL_USUARIO_TBL_TIPO_USUARIO]
    FOREIGN KEY ([TIPU_CODIGO])
    REFERENCES [dbo].[TBL_TIPO_USUARIO]
        ([TIPU_CODIGO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_TBL_USUARIO_TBL_TIPO_USUARIO'
CREATE INDEX [IX_FK_TBL_USUARIO_TBL_TIPO_USUARIO]
ON [dbo].[TBL_USUARIO]
    ([TIPU_CODIGO]);
GO

-- Creating foreign key on [USU_CODIGO] in table 'TBL_VEHICULO'
ALTER TABLE [dbo].[TBL_VEHICULO]
ADD CONSTRAINT [FK_TBL_VEHICULO_TBL_USUARIO]
    FOREIGN KEY ([USU_CODIGO])
    REFERENCES [dbo].[TBL_USUARIO]
        ([USU_CODIGO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_TBL_VEHICULO_TBL_USUARIO'
CREATE INDEX [IX_FK_TBL_VEHICULO_TBL_USUARIO]
ON [dbo].[TBL_VEHICULO]
    ([USU_CODIGO]);
GO

-- Creating foreign key on [DIM_CODIGO] in table 'TBL_PUESTOS'
ALTER TABLE [dbo].[TBL_PUESTOS]
ADD CONSTRAINT [FK_TBL_PUESTOS_TBL_DIMENSION]
    FOREIGN KEY ([DIM_CODIGO])
    REFERENCES [dbo].[TBL_DIMENSION]
        ([DIM_CODIGO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_TBL_PUESTOS_TBL_DIMENSION'
CREATE INDEX [IX_FK_TBL_PUESTOS_TBL_DIMENSION]
ON [dbo].[TBL_PUESTOS]
    ([DIM_CODIGO]);
GO

-- Creating foreign key on [DIM_CODIGO] in table 'TBL_VEHICULO'
ALTER TABLE [dbo].[TBL_VEHICULO]
ADD CONSTRAINT [FK_TBL_VEHICULO_TBL_DIMENSION]
    FOREIGN KEY ([DIM_CODIGO])
    REFERENCES [dbo].[TBL_DIMENSION]
        ([DIM_CODIGO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_TBL_VEHICULO_TBL_DIMENSION'
CREATE INDEX [IX_FK_TBL_VEHICULO_TBL_DIMENSION]
ON [dbo].[TBL_VEHICULO]
    ([DIM_CODIGO]);
GO

-- --------------------------------------------------
-- Script has ended
-- --------------------------------------------------