//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwParqueadero.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ASIGNACION_PARQUEADERO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_ASIGNACION_PARQUEADERO()
        {
            this.TBL_DIA_ASIGNACION = new HashSet<TBL_DIA_ASIGNACION>();
        }
    
        public int ASI_CODIGO { get; set; }
        public string ASI_DESCRIPCION { get; set; }
        public int JOR_CODIGO { get; set; }
        public int SOL_CODIGO { get; set; }
        public int PUE_CODIGO { get; set; }
    
        public virtual TBL_JORNADA TBL_JORNADA { get; set; }
        public virtual TBL_PUESTOS TBL_PUESTOS { get; set; }
        public virtual TBL_SOLICITUD TBL_SOLICITUD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_DIA_ASIGNACION> TBL_DIA_ASIGNACION { get; set; }
    }
}
