//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwParqueadero.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SOLICITUD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_SOLICITUD()
        {
            this.TBL_ASIGNACION_PARQUEADERO = new HashSet<TBL_ASIGNACION_PARQUEADERO>();
            this.TBL_OBSERVACION_SOLICITUD = new HashSet<TBL_OBSERVACION_SOLICITUD>();
            this.TBL_REQUISITOS = new HashSet<TBL_REQUISITOS>();
        }
    
        public int SOL_CODIGO { get; set; }
        public Nullable<System.DateTime> SOL_FECHA_INICIO { get; set; }
        public Nullable<System.DateTime> SOL_FECHA_APROBACION { get; set; }
        public Nullable<int> USU_CODIGO { get; set; }
        public string PER_DESCRIPCION { get; set; }
        public Nullable<bool> SOL_APROBADO { get; set; }
        public string SOL_BANDEJA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_ASIGNACION_PARQUEADERO> TBL_ASIGNACION_PARQUEADERO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_OBSERVACION_SOLICITUD> TBL_OBSERVACION_SOLICITUD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_REQUISITOS> TBL_REQUISITOS { get; set; }
        public virtual TBL_USUARIO TBL_USUARIO { get; set; }
    }
}
