//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwParqueadero.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PUESTOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_PUESTOS()
        {
            this.TBL_ASIGNACION_PARQUEADERO = new HashSet<TBL_ASIGNACION_PARQUEADERO>();
        }
    
        public int PUE_CODIGO { get; set; }
        public string PUE_NOMBRE { get; set; }
        public int DIM_CODIGO { get; set; }
        public int PAR_CODIGO { get; set; }
        public bool PUE_ESTADO_MATUTINA { get; set; }
        public bool PUE_ESTADO_NOCTURNO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_ASIGNACION_PARQUEADERO> TBL_ASIGNACION_PARQUEADERO { get; set; }
        public virtual TBL_PARQUEADERO TBL_PARQUEADERO { get; set; }
        public virtual TBL_DIMENSION TBL_DIMENSION { get; set; }
    }
}
