//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwParqueadero.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_EMPRESA
    {
        public int EMP_CODIGO { get; set; }
        public string EMP_NOMBRE { get; set; }
        public string EMP_CORREO { get; set; }
        public string EMP_SMTP { get; set; }
        public string EMP_PUERTO { get; set; }
        public string EMP_PASSWORD { get; set; }
    }
}
