//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwParqueadero.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_VEHICULO
    {
        public int VEH_CODIGO { get; set; }
        public string VEH_OBSERVACION { get; set; }
        public string VEH_PLACA { get; set; }
        public string VEH_FOTO { get; set; }
        public int MOD_CODIGO { get; set; }
        public int DIM_CODIGO { get; set; }
        public int USU_CODIGO { get; set; }
        public bool VEH_ESTADO { get; set; }
    
        public virtual TBL_MODELO TBL_MODELO { get; set; }
        public virtual TBL_USUARIO TBL_USUARIO { get; set; }
        public virtual TBL_DIMENSION TBL_DIMENSION { get; set; }
    }
}
