//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwParqueadero.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_USUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_USUARIO()
        {
            this.TBL_SOLICITUD = new HashSet<TBL_SOLICITUD>();
            this.TBL_VEHICULO = new HashSet<TBL_VEHICULO>();
        }
    
        public int USU_CODIGO { get; set; }
        public string USU_NOMBRES { get; set; }
        public string USU_APELLIDOS { get; set; }
        public bool USU_ESTADO { get; set; }
        public int TIPU_CODIGO { get; set; }
        public string USU_CEDULA { get; set; }
        public string USU_CORREO { get; set; }
        public string USU_CONTACTO { get; set; }
        public string USU_PASSWORD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_SOLICITUD> TBL_SOLICITUD { get; set; }
        public virtual TBL_TIPO_USUARIO TBL_TIPO_USUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_VEHICULO> TBL_VEHICULO { get; set; }
    }
}
