//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwParqueadero.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PARQUEADERO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_PARQUEADERO()
        {
            this.TBL_PUESTOS = new HashSet<TBL_PUESTOS>();
        }
    
        public int PAR_CODIGO { get; set; }
        public string PAR_DESCRIPCION { get; set; }
        public string PAR_DIRECCION { get; set; }
        public string PAR_ENCARGADO { get; set; }
        public string PAR_CONTACTO { get; set; }
        public int PAR_PUESTOS { get; set; }
        public string PAR_CONTACTO2 { get; set; }
        public string PAR_TELEFONO { get; set; }
        public string PAR_TELEFONO2 { get; set; }
        public string PAR_TELEFONO_ENCARGADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_PUESTOS> TBL_PUESTOS { get; set; }
    }
}
