//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwParqueadero.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DIA_ASIGNACION
    {
        public int ADIA_CODIGO { get; set; }
        public int DIA_CODIGO { get; set; }
        public int ASI_CODIGO { get; set; }
    
        public virtual TBL_ASIGNACION_PARQUEADERO TBL_ASIGNACION_PARQUEADERO { get; set; }
        public virtual TBL_DIAS TBL_DIAS { get; set; }
    }
}
